name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '.github/workflows/**'
env:
  tag: v1.21.50

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get the latest commit message
      run:
        echo "latest_commit_message=$(git reflog -1 --pretty=format:%s)" >> $GITHUB_ENV

    - name: Read changelog
      run: |
        changelog=$(< CHANGELOG.md)
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$changelog" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm i

    - name: Build
      run: |
        tsc --noCheck
        webpack
        echo "filepath=$(node packer.js --print-filepath-only)" >> $GITHUB_ENV
      timeout-minutes: 1

    - name: Publish to artifact
      uses: actions/upload-artifact@v4
      with:
        name: '测试版'
        path: ${{ env.filepath }}
        compression-level: 0

    - name: Release
      if: startsWith(env.latest_commit_message, 'v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.tag }}
        name: Release  ${{ env.latest_commit_message }}
        body: ${{ env.CHANGELOG }}
        draft: false
        prerelease: false
        files: ${{ env.filepath }}