name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get the latest commit message
      id: get_latest_commit
      run: |
        latest_commit=$(git log -1 --pretty=format:%s)
        echo "latest_commit_message=$latest_commit" >> $GITHUB_ENV
        
    - name: Read changelog
      id: read_changelog
      run: |
        changelog=$(< CHANGELOG.md)
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$changelog" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Publish to artifact
      if: ${{ !startsWith(env.latest_commit_message, 'v') }}
      uses: actions/upload-artifact@v4
      with:
        name: '测试版'
        path: build

    - name: Release
      if: startsWith(env.latest_commit_message, 'v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.21.50
        name: Release  ${{ env.latest_commit_message }}
        body: ${{ env.CHANGELOG }}
        draft: false
        prerelease: false
        files: build/*  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}